services:
  model_service:
    build: ./model
    container_name: model-service
    expose:
      - "8000"
    networks:
      - app-network

  chatbot_service:
    build: ./bot
    container_name: chatbot-service
    expose:
      - "8001"
    env_file:
      - .env
    networks:
      - app-network

  gee_service:
    build: ./api
    container_name: gee-service
    expose:
      - "8002"
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend-app
    env_file:
      - .env
    networks:
      - app-network

  server:
    image: nginx:stable-alpine
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - model_service
      - chatbot_service
      - gee_service
      - frontend
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
